### ISSUE TITLE
It errors out when building wheels. Any advice?

### ISSUE THREAD

**Issue by TronVonDoom** [ericdaat/webradio-to-spotify#10]
I've been looking for something like this for a while, so thanks for creating it!

It errors out when building wheels. Any advice?

**Comment by ericdaat** [comment]
Hi 🙂 
Sorry I did not see your issue, I'll look into it and let you know, I haven't run this code in a while!

**Comment by ericdaat** [comment]
@TronVonDoom it seems to be working for me, but I found other bugs and some unclear things in the doc, I'll revamp this project a little and update a few things. Let me know if it helps 🙂
